name: 🔮 Sync Mirror

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Gitee
        uses: jikkai/sync-gitee@v1
        with:
            repository: jikkai/sync-gitee
            username: ${{ secrets.GITEE_USERNAME }}
            password: ${{ secrets.GITEE_PASSWORD }}
            tags: true
            branches: main dev
